name: Sync to secondary GitHub repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "ymanchon"
        git config --global user.email "yann@pym.fr"

    - name: Push to secondary repository
      env:
        SECOND_REPO_PAT: ${{ secrets.LIBNSL_YMANCHON_REPO }}
      run: |
        git remote add second-repo https://ymanchon:${LIBNSL_YMANCHON_REPO}@github.com/ymanchon/LibNSL.git
        git push second-repo main --force
